### PR TITLE
[21209] Bump version to 2.14.2

### PR DESCRIPTION
**Pull request by EduPonz**
## Description

This PR:

1. Bumps version to v2.14.2
2. Adds Fast DDS v2.14.2 release notes

## Contributor Checklist

- [x] Commit messages follow the project guidelines. 
- _N/A_: Code snippets related to the added documentation have been provided.
- [x] Documentation tests pass locally.
- _N/A_: Applicable backports have been included in the description.

## Reviewer Checklist

- [x] The PR has a milestone assigned.
- [x] The title and description correctly express the PR's purpose.
- [x] Check contributor checklist is correct.
- [x] CI passes without warnings or errors.

### CODE REVIEW

**Comment by EduPonz** [comment]
@richiprosima please test docs

**Comment by EduPonz** [comment]
@richiprosima please test docs

**Review by elianalf — CHANGES_REQUESTED** [review]
Could you please remove (latest) also from docs/notes/previous_versions/v2.14.0.rst ?

**Comment by EduPonz** [comment]
@richiprosima please test docs

**Review by elianalf — APPROVED** [review]

**Pull request merged**
