### PR TITLE
[20709] Remove RTPSMessageGroup from aliases-api includes

### PR DESCRIPTION
**Pull request by elianalf**
## Description

Remove RTPSMessageGroup from aliases-api includes.
Related PR in Fast DDS:
* https://github.com/eProsima/Fast-DDS/pull/4657

## Contributor Checklist

- [x] Commit messages follow the project guidelines. 
- N/A Code snippets related to the added documentation have been provided.
- N/A Documentation tests pass locally.
- N/A Applicable backports have been included in the description.

## Reviewer Checklist

- [x] The PR has a milestone assigned.
- [x] The title and description correctly express the PR's purpose.
- [x] Check contributor checklist is correct.
- [x] CI passes without warnings or errors.

### CODE REVIEW

**Comment by elianalf** [comment]
@richiprosima please test_3 this

**Comment by EduPonz** [comment]
@richiprosima please test_3 this

**Review by EduPonz — DISMISSED** [review]

**Comment by elianalf** [comment]
@richiprosima please test_3 this

**Review by EduPonz — APPROVED** [review]

**Comment by EduPonz** [comment]
@richiprosima please test_3 this

**Pull request merged**
