### PR TITLE
Correct CMake Windows installation from sources

### LINKED ISSUE #338: Building Fast-DDS with eProsima/Foonathan cause a link error [13853]
Hi,

I am trying to integrate FastDDS with it's dependencies on my CMake project and I get some linkage errors.

I tried diving in and I see for start that the foonathan instructions have some issues:
according to the docs:
```
cmake -DCMAKE_INSTALL_PREFIX=%USERPROFILE%/Fast-DDS/install ^
   -DBUILD_SHARED_LIBS=OFF -DFOONATHAN_MEMORY_BUILD_TOOLS=ON ^
   -DCMAKE_POSITION_INDEPENDENT_CODE=ON -DFOONATHAN_MEMORY_BUILD_TESTS=OFF ..
```
While looking on https://github.com/eProsima/foonathan_memory_vendor I see this issues:
Option FOONATHAN_MEMORY_BUILD_TOOLS does not exist and should be BUILD_MEMORY_TOOLS
Option FOONATHAN_MEMORY_BUILD_TESTS does not exist and should be BUILD_MEMORY_TESTS    

CMAKE_POSITION_INDEPENDENT_CODE does not exist and is set automatically when BUILD_SHARED_LIBS=ON
No option exist for it. 
The comment say 
```
if(BUILD_SHARED_LIBS)
    # Library will be statically created with PIC code
```

If the user chose shared lib it will be statically created?
https://github.com/eProsima/foonathan_memory_vendor/blob/da062db05975d24a4b53de5a4122b47f6824997f/CMakeLists.txt#L30

The issues I get on my build is :
```
/usr/bin/ld: ../../fastdds/fastdds_install/lib/libfastrtps.a(IPLocator.cpp.o): relocation R_X86_64_TPOFF32 against symbol `_ZN4asio6detail15keyword_tss_ptrINS0_10call_stackINS0_14thread_contextENS0_16thread_info_baseEE7contextEE6value_E' can not be used when making a shared object; recompile with -fPIC
```

Is that familiar?
Any help on overcoming it?
My CMake source code is here:

https://github.com/Nir-Az/librealsense/blob/link_fastcdr/CMake/external_fastdds.cmake

Thanks

### PR DESCRIPTION
**Pull request by EduPonz**
Correct Windows installation from sources when using CMake

* Depends on eProsima/foonathan_memory_vendor#55
* Closes #338

### CODE REVIEW

**Review by MiguelCompany — DISMISSED** [review]
LGTM

**Review by MiguelBarro — DISMISSED** [review]
LGTM

**Review by MiguelBarro — APPROVED** [review]
LGTM

**Comment by EduPonz** [comment]
I do not know why Jenkins is not updating the check state.

* CI run: [Build Status](http://jenkins.eprosima.com:8080/job/fastdds_docs_manual/299/)

**Pull request merged**
