### PR TITLE
[20723] Include v2.13.4 release notes

### PR DESCRIPTION
**Pull request by JesusPoderoso**
## Description

This PR includes the release notes of Fast DDS v2.13.4 in latest documentation (master)

## Contributor Checklist

- [x] Commit messages follow the project guidelines. 
- **N/A** Code snippets related to the added documentation have been provided.
- [x] Documentation tests pass locally.
- **N/A** Applicable backports have been included in the description.

## Reviewer Checklist

- [x] The PR has a milestone assigned.
- [x] The title and description correctly express the PR's purpose.
- [x] Check contributor checklist is correct.
- [x] CI passes without warnings or errors.

### CODE REVIEW

**Comment by JesusPoderoso** [comment]
@richiprosima please test this

**Comment by Mario-DL** [comment]
We may be missing to update `docs/notes/versions.rst` Shapes Demo related version in `2.13.x` to `v2.13.4`

**Comment by JesusPoderoso** [comment]
@richiprosima please test this

**Review by Mario-DL — APPROVED** [review]
LGTM with Green CI

**Review by EduPonz — APPROVED** [review]

**Pull request merged**
