### PR TITLE
TypeObjectRegistry refactor [21135]

### PR DESCRIPTION
**Pull request by richiware**
## Description

This PR only regenerate the IDL files.

Related implementation PR:

- eprosima/fast-dds#4874

## Contributor Checklist

- [x] Commit messages follow the project guidelines. 
- *N/A* Code snippets related to the added documentation have been provided.
- [x] Documentation tests pass locally.
- *N/A* Applicable backports have been included in the description.

## Reviewer Checklist

- [x] The PR has a milestone assigned.
- [x] The title and description correctly express the PR's purpose.
- [x] Check contributor checklist is correct.
- [x] CI passes without warnings or errors.

### CODE REVIEW

**Comment by richiware** [comment]
@richiprosima  please test_3 docs

**Comment by richiware** [comment]
@richiprosima please test_3 docs

**Review by adriancampo — APPROVED** [review]
LGTM

**Comment by richiware** [comment]
@richiprosima please test_3 docs

**Pull request merged**
