### PR TITLE
[21366] Bump version to v3.0.0

### PR DESCRIPTION
**Pull request by elianalf**
## Description

This PR bumps the project version to 3.0.0 and adds the corresponding release notes.

## Contributor Checklist

- [x] Commit messages follow the project guidelines. 
- N/A Code snippets related to the added documentation have been provided.
- [x] Documentation tests pass locally.
-N/A Applicable backports have been included in the description.

## Reviewer Checklist

- [x] The PR has a milestone assigned.
- [x] The title and description correctly express the PR's purpose.
- [x] Check contributor checklist is correct.
- [x] CI passes without warnings or errors.

### CODE REVIEW

**Review by Mario-DL — CHANGES_REQUESTED** [review]
Notes LGTM 

I think we should also remove the warning here https://github.com/eProsima/Fast-DDS-docs/blob/caf9c95f0d2b74e971529c073b3d42637d954e3d/docs/02-formalia/titlepage.rst?plain=1#L7

**Comment by Mario-DL** [comment]
We will also wait for the rest of the PRs pending to merge in Fast DD

**Review by Mario-DL — CHANGES_REQUESTED** [review]
I am missing [Update fastcdr thirdparty](https://github.com/eProsima/Fast-DDS/pull/5123) and [Add new tests for testing new key hash...](https://github.com/eProsima/Fast-DDS/pull/5091)

**Comment by JesusPoderoso** [comment]
> I am missing [Update fastcdr thirdparty](https://github.com/eProsima/Fast-DDS/pull/5123) and [Add new tests for testing new key hash...](https://github.com/eProsima/Fast-DDS/pull/5091)

The xTypes fix was introduced previously, in line 28. Fast cdr submodule update introduced in commit [ccb8138](https://github.com/eProsima/Fast-DDS-docs/pull/884/commits/ccb8138cbc6b5c75efd414055f8fcc4f3bc8ce96)

**Review by Mario-DL — DISMISSED** [review]
LGTM with Green CI

**Review by Mario-DL — APPROVED** [review]
LGTM with green CI

**Review by MiguelCompany — APPROVED** [review]

**Pull request merged**
