### PR TITLE
[20955] Prepare for 2.10.4 release

### PR DESCRIPTION
**Pull request by MiguelCompany**
## Description

Bump version and release notes for 2.10.4.

## Contributor Checklist

- [x] Commit messages follow the project guidelines. 
- _N/A_ Code snippets related to the added documentation have been provided.
- [x] Documentation tests pass locally.
- _N/A_ Applicable backports have been included in the description.

## Reviewer Checklist

- [x] The PR has a milestone assigned.
- [x] The title and description correctly express the PR's purpose.
- [x] Check contributor checklist is correct.
- [x] CI passes without warnings or errors.

### CODE REVIEW

**Comment by MiguelCompany** [comment]
@richiprosima Please test docs

**Review by Mario-DL — COMMENTED** [review]
LGTM with green CI, just waiting for [eProsima/Fast-DDS/4826 ](https://github.com/eProsima/Fast-DDS/pull/4826) in case we would want to include it

**Review by Mario-DL — DISMISSED** [review]
LGTM with green CI

**Comment by MiguelCompany** [comment]
@richiprosima Please test docs

**Review by Mario-DL — APPROVED** [review]

**Pull request merged**
