### PR TITLE
[20995] Add notes from v2.10.4

### PR DESCRIPTION
**Pull request by MiguelCompany**
## Description

This adds the notes from release v2.10.4

@Mergifyio backport 2.14.x 2.13.x

## Contributor Checklist

- [x] Commit messages follow the project guidelines. 
- _N/A_ Code snippets related to the added documentation have been provided.
- [x] Documentation tests pass locally.
- [x] Applicable backports have been included in the description.

## Reviewer Checklist

- [x] The PR has a milestone assigned.
- [x] The title and description correctly express the PR's purpose.
- [x] Check contributor checklist is correct.
- [x] CI passes without warnings or errors.

### CODE REVIEW

**Comment by JesusPoderoso** [comment]
@richiprosima please test_3 this

**Review by JesusPoderoso — CHANGES_REQUESTED** [review]
We should update also [this](https://github.com/eProsima/Fast-DDS-docs/blob/e9b29848391c32318146414d69fff301a5983216/docs/notes/versions.rst?plain=1#L299) with `v1.0.28`, ans [this](https://github.com/eProsima/Fast-DDS-docs/blob/e9b29848391c32318146414d69fff301a5983216/docs/notes/versions.rst?plain=1#L383) with `v2.10.4`

**Comment by MiguelCompany** [comment]
> We should update also [this](https://github.com/eProsima/Fast-DDS-docs/blob/e9b29848391c32318146414d69fff301a5983216/docs/notes/versions.rst?plain=1#L299) with `v1.0.28`, ans [this](https://github.com/eProsima/Fast-DDS-docs/blob/e9b29848391c32318146414d69fff301a5983216/docs/notes/versions.rst?plain=1#L383) with `v2.10.4`

0fa2490

**Comment by MiguelCompany** [comment]
@richiprosima Please test_3 this

**Review by JesusPoderoso — DISMISSED** [review]
LGTM with green CI

**Comment by JesusPoderoso** [comment]
@Mergifyio backport 2.14.x 2.13.x

**Comment by MiguelCompany** [comment]
@richiprosima Please test_3 this

**Comment by MiguelCompany** [comment]
@richiprosima Please test_3 this

**Review by JesusPoderoso — APPROVED** [review]

**Pull request merged**
