### PR TITLE
Update Ros2 configuration [10478]

### PR DESCRIPTION
**Pull request by IkerLuengo**
Complete the ROS2 configuration section.

### CODE REVIEW

**Comment by richiware** [comment]
Build status: [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Docs%20Manual/735/)

**Comment by richiware** [comment]
Build status: [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Docs%20Manual/736/)

**Review by EduPonz — APPROVED** [review]
LGTM

**Review by EduPonz — DISMISSED** [review]

**Comment by richiware** [comment]
Build status: [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Docs%20Manual/738/)

**Comment by richiware** [comment]
Build status: [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Docs%20Manual/740/)

**Review by EduPonz — APPROVED** [review]

**Pull request merged**
