### PR TITLE
Updated breathe python module and fixed namespaces

### PR DESCRIPTION
**Pull request by rsanchez15**
Signed-off-by: RaulSanchez <raul@eprosima.com>

### CODE REVIEW

**Comment by richiprosima** [comment]
Build status: [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Docs%20Manual/781/)

**Review by JLBuenoLopez-eProsima — APPROVED** [review]
LGTM.

I have checked that it works as expected locally.

**Comment by richiprosima** [comment]
Build status: [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Docs%20Manual/783/)

**Comment by richiprosima** [comment]
Build status: [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Docs%20Manual/784/)

**Comment by richiprosima** [comment]
Build status: [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Docs%20Manual/787/)

**Comment by richiprosima** [comment]
Build status: [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Docs%20Manual/799/)

**Pull request merged**
