### PR TITLE
[21131] Added test_shared_mem_transport_descriptor to api_reference

### PR DESCRIPTION
**Pull request by Mario-DL**
## Description

As `test_SharedMemTransportDescriptor` is now public, we need to add it to the `api_reference`

Related implementation PR:
* eProsima/Fast-DDS#4953

## Contributor Checklist

- [X] Commit messages follow the project guidelines. 
- [X] Code snippets related to the added documentation have been provided.
- [X] Documentation tests pass locally.
- __NO__ Applicable backports have been included in the description.

## Reviewer Checklist

- [x] The PR has a milestone assigned.
- [x] The title and description correctly express the PR's purpose.
- [x] Check contributor checklist is correct.
- [x] CI passes without warnings or errors.

### CODE REVIEW

**Comment by Mario-DL** [comment]
@richiprosima please test_3 docs

**Review by elianalf — APPROVED** [review]

**Comment by Mario-DL** [comment]
@richiprosima please test_3 docs

**Comment by Mario-DL** [comment]
@richiprosima please test_3 docs

**Comment by EduPonz** [comment]
@richiprosima please test_3 docs

**Pull request merged**
