### PR TITLE
[20629] GUIDLess Discovery Server

### PR DESCRIPTION
**Pull request by cferreiragonz**
## Description
This PR updates documentation explaining the new architecture of Discovery Server introduced in:

-  https://github.com/eProsima/Fast-DDS/pull/4716
- https://github.com/eProsima/Discovery-Server/pull/76

And needs to be merged after them.
It also updates the XML profiles and examples that use the Fast DDS CLI or the Discovery Server discovery protocol.

## Contributor Checklist

- [X] Commit messages follow the project guidelines. 
- [X] Code snippets related to the added documentation have been provided.
- [X] Documentation tests pass locally.
- _N/A_ Applicable backports have been included in the description.

## Reviewer Checklist

- [x] The PR has a milestone assigned.
- [x] The title and description correctly express the PR's purpose.
- [x] Check contributor checklist is correct.
- [ ] CI passes without warnings or errors.

### CODE REVIEW

**Review by MiguelCompany — CHANGES_REQUESTED** [review]

**Comment by cferreiragonz** [comment]
@richiprosima please test this

**Comment by cferreiragonz** [comment]
@richiprosima please test this

**Review by MiguelCompany — APPROVED** [review]

**Comment by MiguelCompany** [comment]
@richiprosima Please test_3 docs

**Comment by cferreiragonz** [comment]
@richiprosima Please test_3 docs

**Review by MiguelCompany — APPROVED** [review]

**Pull request merged**
