### PR TITLE
Changes on recomended statistics DataWriterQoS [12520]

### PR DESCRIPTION
**Pull request by MiguelCompany**
This PR includes the required documentation changes for eProsima/Fast-DDS#2176 and eProsima/Fast-DDS#2180

Depends on #284

### CODE REVIEW

**Review by JLBuenoLopez-eProsima — CHANGES_REQUESTED** [review]
This PR is not even building. CI is complaining about building the new flow controller example.

**Comment by MiguelCompany** [comment]
> This PR is not even building. CI is complaining about building the new flow controller example.

Yeah. We should wait for it to be rebased after #284

**Comment by MiguelCompany** [comment]
@JLBuenoLopez-eProsima this has been rebased

**Review by JLBuenoLopez-eProsima — APPROVED** [review]
LGTM with green CI.

Good catch the `name` type and default value :sweat_smile:

**Pull request merged**
