### PR TITLE
WIP: Added XML topic profile section [9225]

### PR DESCRIPTION
**Pull request by rsanchez15**
Added Topic profile section and updated `<topic>` documentation in common XML configuration elements.
This PR provides additional support to https://github.com/eProsima/Fast-DDS/issues/1369.

### CODE REVIEW

**Comment by richiware** [comment]
Build status: [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Docs%20Manual/612/)

**Review by IkerLuengo — APPROVED** [review]
LGTM

**Comment by richiware** [comment]
Build status: [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Docs%20Manual/739/)

**Comment by MiguelCompany** [comment]
@rsanchez15 This needs a rebase

**Comment by JLBuenoLopez-eProsima** [comment]
@rsanchez15 can we close this PR? I think that with the refactor we intend to perform in the XML section, this can be reworked.

**Pull request closed without merging**
