### PR TITLE
[21290] Update to doxygen 1.9.8 used in Ubuntu 24.04

### PR DESCRIPTION
**Pull request by richiware**
## Description

This PR updates doxygen configuration file to version 1.9.8 which is provided by Ubuntu 24.04.

## Contributor Checklist

- [x] Commit messages follow the project guidelines. 
- **N/A** Code snippets related to the added documentation have been provided.
- [x] Documentation tests pass locally.
- **N/A** Applicable backports have been included in the description.

## Reviewer Checklist

- [x] The PR has a milestone assigned.
- [x] The title and description correctly express the PR's purpose.
- [x] Check contributor checklist is correct.
- [x] CI passes without warnings or errors.

### CODE REVIEW

**Comment by richiware** [comment]
@richiprosima please test_3 this

**Comment by JesusPoderoso** [comment]
@mergifyio rebase master

**Comment by JesusPoderoso** [comment]
@Mergifyio rebase master

**Comment by JesusPoderoso** [comment]
I've triggered a [manual run here](https://github.com/eProsima/Fast-DDS-docs/actions/runs/9789148590) using `ubuntu-24.04`.
Waiting that CI to be green

**Review by JesusPoderoso — APPROVED** [review]

**Pull request merged**
