### PR TITLE
[21053] Move DR TypeConsistencyEnforcement & DataRepresentation from TypeConsistency to DataReaderQos

### PR DESCRIPTION
**Pull request by JesusPoderoso**
## Description

This PR updates and improves the documentation of TypeConsistency and DataRepresentation QoS policies

## Contributor Checklist

- [x] Commit messages follow the project guidelines. 
- [x] Code snippets related to the added documentation have been provided.
- [x] Documentation tests pass locally.
- **N/A** Applicable backports have been included in the description.

## Reviewer Checklist

- [x] The PR has a milestone assigned.
- [x] The title and description correctly express the PR's purpose.
- [x] Check contributor checklist is correct.
- [x] CI passes without warnings or errors.

### CODE REVIEW

**Comment by JesusPoderoso** [comment]
@richiprosima please test_3 this

**Comment by JesusPoderoso** [comment]
@richiprosima please test_3 this

**Review by Mario-DL — CHANGES_REQUESTED** [review]
We would need to change the references to `eprosima::fastdds::dds::TypeConsistencyQos` to `eprosima::fastdds::dds::TypeConsistencyEnforcementQos`, for instance, in the `docs/fastdds/api_reference/dds_pim/subscriber/typeconsistencyqos.rst`.
Also in the `DDSCodeTester` there are some declarations `consistency_qos.representation` that should be changed to `representation()`

**Comment by JesusPoderoso** [comment]
@richiprosima please test_3 this

**Comment by JesusPoderoso** [comment]
@richiprosima please test_3 this

**Comment by JesusPoderoso** [comment]
@richiprosima please test_3 this

**Comment by JesusPoderoso** [comment]
@richiprosima please test_3 this

**Comment by JesusPoderoso** [comment]
@richiprosima please test_3 this

**Review by Mario-DL — APPROVED** [review]
LGTM

**Pull request merged**
